services:
  eureka-server:
    image: eureka-microservice:v1
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      SPRING_APPLICATION_NAME: Eureka-Server
      EUREKA_REGISTER_WITH_EUREKA: false
      EUREKA_FETCH_REGISTRY: false
      EUREKA_SELF_PRESERVATION: true
      EUREKA_LOG_LEVEL: INFO
      DISCOVERY_LOG_LEVEL: INFO

    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    networks:
      - ecommerce-network


networks:
  ecommerce-network:
    driver: bridge